/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ObjecoesRouteImport } from './routes/objecoes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DevWebhookRouteImport } from './routes/dev-webhook'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AprendizadosRouteImport } from './routes/aprendizados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiN8nProxyRouteImport } from './routes/api/n8n/proxy'
import { Route as ApiN8nInboundWhatsappRouteImport } from './routes/api/n8n/inbound-whatsapp'
import { Route as ApiPublicN8nInboundWhatsappRouteImport } from './routes/api/public/n8n/inbound-whatsapp'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjecoesRoute = ObjecoesRouteImport.update({
  id: '/objecoes',
  path: '/objecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DevWebhookRoute = DevWebhookRouteImport.update({
  id: '/dev-webhook',
  path: '/dev-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendizadosRoute = AprendizadosRouteImport.update({
  id: '/aprendizados',
  path: '/aprendizados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nProxyRoute = ApiN8nProxyRouteImport.update({
  id: '/api/n8n/proxy',
  path: '/api/n8n/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nInboundWhatsappRoute = ApiN8nInboundWhatsappRouteImport.update({
  id: '/api/n8n/inbound-whatsapp',
  path: '/api/n8n/inbound-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nInboundWhatsappRoute =
  ApiPublicN8nInboundWhatsappRouteImport.update({
    id: '/api/public/n8n/inbound-whatsapp',
    path: '/api/public/n8n/inbound-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprendizados': typeof AprendizadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/crm': typeof CrmRoute
  '/dev-webhook': typeof DevWebhookRoute
  '/inbox': typeof InboxRoute
  '/objecoes': typeof ObjecoesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/n8n/inbound-whatsapp': typeof ApiN8nInboundWhatsappRoute
  '/api/n8n/proxy': typeof ApiN8nProxyRoute
  '/api/public/n8n/inbound-whatsapp': typeof ApiPublicN8nInboundWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprendizados': typeof AprendizadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/crm': typeof CrmRoute
  '/dev-webhook': typeof DevWebhookRoute
  '/inbox': typeof InboxRoute
  '/objecoes': typeof ObjecoesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/n8n/inbound-whatsapp': typeof ApiN8nInboundWhatsappRoute
  '/api/n8n/proxy': typeof ApiN8nProxyRoute
  '/api/public/n8n/inbound-whatsapp': typeof ApiPublicN8nInboundWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprendizados': typeof AprendizadosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/crm': typeof CrmRoute
  '/dev-webhook': typeof DevWebhookRoute
  '/inbox': typeof InboxRoute
  '/objecoes': typeof ObjecoesRoute
  '/usuarios': typeof UsuariosRoute
  '/api/n8n/inbound-whatsapp': typeof ApiN8nInboundWhatsappRoute
  '/api/n8n/proxy': typeof ApiN8nProxyRoute
  '/api/public/n8n/inbound-whatsapp': typeof ApiPublicN8nInboundWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprendizados'
    | '/configuracoes'
    | '/conhecimento'
    | '/crm'
    | '/dev-webhook'
    | '/inbox'
    | '/objecoes'
    | '/usuarios'
    | '/api/n8n/inbound-whatsapp'
    | '/api/n8n/proxy'
    | '/api/public/n8n/inbound-whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprendizados'
    | '/configuracoes'
    | '/conhecimento'
    | '/crm'
    | '/dev-webhook'
    | '/inbox'
    | '/objecoes'
    | '/usuarios'
    | '/api/n8n/inbound-whatsapp'
    | '/api/n8n/proxy'
    | '/api/public/n8n/inbound-whatsapp'
  id:
    | '__root__'
    | '/'
    | '/aprendizados'
    | '/configuracoes'
    | '/conhecimento'
    | '/crm'
    | '/dev-webhook'
    | '/inbox'
    | '/objecoes'
    | '/usuarios'
    | '/api/n8n/inbound-whatsapp'
    | '/api/n8n/proxy'
    | '/api/public/n8n/inbound-whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendizadosRoute: typeof AprendizadosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  CrmRoute: typeof CrmRoute
  DevWebhookRoute: typeof DevWebhookRoute
  InboxRoute: typeof InboxRoute
  ObjecoesRoute: typeof ObjecoesRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiN8nInboundWhatsappRoute: typeof ApiN8nInboundWhatsappRoute
  ApiN8nProxyRoute: typeof ApiN8nProxyRoute
  ApiPublicN8nInboundWhatsappRoute: typeof ApiPublicN8nInboundWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objecoes': {
      id: '/objecoes'
      path: '/objecoes'
      fullPath: '/objecoes'
      preLoaderRoute: typeof ObjecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-webhook': {
      id: '/dev-webhook'
      path: '/dev-webhook'
      fullPath: '/dev-webhook'
      preLoaderRoute: typeof DevWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizados': {
      id: '/aprendizados'
      path: '/aprendizados'
      fullPath: '/aprendizados'
      preLoaderRoute: typeof AprendizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/proxy': {
      id: '/api/n8n/proxy'
      path: '/api/n8n/proxy'
      fullPath: '/api/n8n/proxy'
      preLoaderRoute: typeof ApiN8nProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/inbound-whatsapp': {
      id: '/api/n8n/inbound-whatsapp'
      path: '/api/n8n/inbound-whatsapp'
      fullPath: '/api/n8n/inbound-whatsapp'
      preLoaderRoute: typeof ApiN8nInboundWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/inbound-whatsapp': {
      id: '/api/public/n8n/inbound-whatsapp'
      path: '/api/public/n8n/inbound-whatsapp'
      fullPath: '/api/public/n8n/inbound-whatsapp'
      preLoaderRoute: typeof ApiPublicN8nInboundWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendizadosRoute: AprendizadosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  CrmRoute: CrmRoute,
  DevWebhookRoute: DevWebhookRoute,
  InboxRoute: InboxRoute,
  ObjecoesRoute: ObjecoesRoute,
  UsuariosRoute: UsuariosRoute,
  ApiN8nInboundWhatsappRoute: ApiN8nInboundWhatsappRoute,
  ApiN8nProxyRoute: ApiN8nProxyRoute,
  ApiPublicN8nInboundWhatsappRoute: ApiPublicN8nInboundWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
